/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package teacherDashboard;
import controller.StudentController;
import model.Student;

/**
 *
 * @author inishbashyal
 */
public class TeacherHome extends javax.swing.JFrame {

    /**
     * Creates new form TeacherHome
     */
    public TeacherHome() {
        initComponents();
        home_Panel.setVisible(true);
        add_Student_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Attendance_Panel.setVisible(false);
        attendance_List_Panel.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        layered_Panel = new javax.swing.JLayeredPane();
        home_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        add_Student_Panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        courseName_Label = new javax.swing.JLabel();
        semester_ComboBox = new javax.swing.JComboBox<>();
        semester_Label = new javax.swing.JLabel();
        courseName_ComboBox = new javax.swing.JComboBox<>();
        student_FirstName_Label = new javax.swing.JLabel();
        student_FirstName_TextField = new javax.swing.JTextField();
        student_LastName_TextField = new javax.swing.JTextField();
        student_LastName_Label = new javax.swing.JLabel();
        email_Label = new javax.swing.JLabel();
        student_email_TextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        student_Gender_ComboBox = new javax.swing.JComboBox<>();
        student_Password_Label = new javax.swing.JLabel();
        student_Password_PasswordField = new javax.swing.JPasswordField();
        student_ConfirmPassword_Label = new javax.swing.JLabel();
        student_ConfirmPassword_PasswordField = new javax.swing.JPasswordField();
        student_DateOfBirth_Label = new javax.swing.JLabel();
        student_DateOfBirth_TextField = new javax.swing.JTextField();
        student_MobileNumber_Label = new javax.swing.JLabel();
        student_Mobile_TextField = new javax.swing.JTextField();
        parents_Email_Label = new javax.swing.JLabel();
        parents_Email_TextField = new javax.swing.JTextField();
        parents_Mobile_Label = new javax.swing.JLabel();
        parents_mobile_TextField = new javax.swing.JTextField();
        save_AddStudent_Button = new javax.swing.JButton();
        reset_AddStudent_Button = new javax.swing.JButton();
        student_List_Panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        firstName_StudentList_Label = new javax.swing.JLabel();
        firstName_StudentList_TextField = new javax.swing.JTextField();
        lastName_StudentList_TextField = new javax.swing.JTextField();
        lastName_StudentList_Label = new javax.swing.JLabel();
        email_StudentList_TextField = new javax.swing.JTextField();
        email_StudentList_Label = new javax.swing.JLabel();
        search_StudentList_Button = new javax.swing.JButton();
        reset_StudentList_Button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentList_Table = new javax.swing.JTable();
        new_StudentList_Button = new javax.swing.JButton();
        delete_StudentList_Button = new javax.swing.JButton();
        add_Attendance_Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        date_AddAttendance_Calendar = new com.toedter.calendar.JDateChooser();
        submit_AddAttendance_Button = new javax.swing.JButton();
        reset_AddAttendance_Button = new javax.swing.JButton();
        layeredPanel_AddAttendance = new javax.swing.JLayeredPane();
        AttendancePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Attendance_Table = new javax.swing.JTable();
        save_AttendancePanel_Button = new javax.swing.JButton();
        reset_AttendancePanel_Button = new javax.swing.JButton();
        attendance_List_Panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendance_List_Table = new javax.swing.JTable();
        subjectName_AttendanceList_Label = new javax.swing.JLabel();
        studentName_AttendanceList_TextField = new javax.swing.JTextField();
        studentName_AttendanceList_Label = new javax.swing.JLabel();
        subjectName_AttendanceList_TextField = new javax.swing.JTextField();
        search_AttendanceList_Button = new javax.swing.JButton();
        reset_AttendanceList_Button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        home_Menu = new javax.swing.JMenu();
        home_MenuItem = new javax.swing.JMenuItem();
        student_menu = new javax.swing.JMenu();
        addStudent_MenuItem = new javax.swing.JMenuItem();
        studentList_MenuItem = new javax.swing.JMenuItem();
        attendance_Menu = new javax.swing.JMenu();
        addAttendance_MenuItem = new javax.swing.JMenuItem();
        attendanceList_MenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Home");

        javax.swing.GroupLayout home_PanelLayout = new javax.swing.GroupLayout(home_Panel);
        home_Panel.setLayout(home_PanelLayout);
        home_PanelLayout.setHorizontalGroup(
                home_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(home_PanelLayout.createSequentialGroup()
                                .addGap(330, 330, 330)
                                .addComponent(jLabel1)
                                .addContainerGap(653, Short.MAX_VALUE))
        );
        home_PanelLayout.setVerticalGroup(
                home_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(home_PanelLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel1)
                                .addContainerGap(502, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Add Student");

        courseName_Label.setText("Course Name");

        semester_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        semester_Label.setText("Semester");

        courseName_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        student_FirstName_Label.setText("First Name");

        student_LastName_Label.setText("Last Name");

        email_Label.setText("Email ID :");

        student_email_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_email_TextFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Gender :");

        student_Gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        student_Password_Label.setText("Password");

        student_ConfirmPassword_Label.setText("Confirm Password");

        student_DateOfBirth_Label.setText("Date of Birth");

        student_DateOfBirth_TextField.setText("dd/mm/yyyy");

        student_MobileNumber_Label.setText("Mobile Number");

        parents_Email_Label.setText("Parent's Email");

        parents_Mobile_Label.setText("Parent's Mobile No.");

        save_AddStudent_Button.setBackground(new java.awt.Color(0, 0, 255));
        save_AddStudent_Button.setForeground(new java.awt.Color(255, 255, 255));
        save_AddStudent_Button.setText("SAVE");
        save_AddStudent_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_AddStudent_ButtonActionPerformed(evt);
            }
        });

        reset_AddStudent_Button.setBackground(new java.awt.Color(0, 0, 255));
        reset_AddStudent_Button.setForeground(new java.awt.Color(255, 255, 255));
        reset_AddStudent_Button.setText("RESET");

        javax.swing.GroupLayout add_Student_PanelLayout = new javax.swing.GroupLayout(add_Student_Panel);
        add_Student_Panel.setLayout(add_Student_PanelLayout);
        add_Student_PanelLayout.setHorizontalGroup(
                add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                        .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(courseName_Label)
                                                                                .addComponent(student_FirstName_Label))
                                                                        .addGap(35, 35, 35)
                                                                        .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(courseName_ComboBox, 0, 290, Short.MAX_VALUE)
                                                                                .addComponent(student_FirstName_TextField)))
                                                                .addComponent(email_Label)
                                                                .addComponent(student_email_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(student_Password_Label)
                                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(parents_Email_Label)
                                                                                        .addComponent(student_DateOfBirth_Label))))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(student_Password_PasswordField)
                                                                                        .addComponent(student_DateOfBirth_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)))
                                                                        .addComponent(parents_Email_TextField))))
                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                .addGap(88, 88, 88)
                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                                .addComponent(student_LastName_Label)
                                                                                .addGap(35, 35, 35)
                                                                                .addComponent(student_LastName_TextField))
                                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                                .addComponent(jLabel15)
                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                        .addComponent(student_Gender_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                                .addComponent(semester_Label)
                                                                                .addGap(34, 34, 34)
                                                                                .addComponent(semester_ComboBox, 0, 326, Short.MAX_VALUE))))
                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                .addGap(68, 68, 68)
                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(student_ConfirmPassword_Label)
                                                                        .addComponent(student_MobileNumber_Label)
                                                                        .addComponent(parents_Mobile_Label))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(student_ConfirmPassword_PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                                                        .addComponent(student_Mobile_TextField)
                                                                        .addComponent(parents_mobile_TextField))))))
                                .addGap(79, 79, 79))
                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(save_AddStudent_Button)
                                .addGap(137, 137, 137)
                                .addComponent(reset_AddStudent_Button)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        add_Student_PanelLayout.setVerticalGroup(
                add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(37, 37, 37)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(courseName_Label)
                                        .addComponent(semester_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(semester_Label)
                                        .addComponent(courseName_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(student_FirstName_Label)
                                        .addComponent(student_FirstName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(student_LastName_Label)
                                        .addComponent(student_LastName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(email_Label)
                                        .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(student_Gender_ComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(student_email_TextField))
                                .addGap(18, 18, 18)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(student_Password_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(student_Password_Label)
                                        .addComponent(student_ConfirmPassword_Label)
                                        .addComponent(student_ConfirmPassword_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(student_DateOfBirth_Label)
                                        .addComponent(student_DateOfBirth_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(student_MobileNumber_Label)
                                        .addComponent(student_Mobile_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(parents_Email_Label)
                                        .addComponent(parents_Email_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(parents_Mobile_Label)
                                        .addComponent(parents_mobile_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(save_AddStudent_Button)
                                        .addComponent(reset_AddStudent_Button))
                                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setText("Student List");

        firstName_StudentList_Label.setText("First Name");

        lastName_StudentList_Label.setText("Last Name");

        email_StudentList_Label.setText("Email");

        search_StudentList_Button.setBackground(new java.awt.Color(0, 0, 255));
        search_StudentList_Button.setForeground(new java.awt.Color(255, 255, 255));
        search_StudentList_Button.setText("SEARCH");

        reset_StudentList_Button.setBackground(new java.awt.Color(0, 0, 255));
        reset_StudentList_Button.setForeground(new java.awt.Color(255, 255, 255));
        reset_StudentList_Button.setText("RESET");

        studentList_Table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "Select All", "#", "Course Name", "Semester", "Roll No.", "Name", "Email", "Date Of Birth", "Gender", "Mobile", "Father Email Id", "Father Mobile", "Action"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(studentList_Table);

        new_StudentList_Button.setBackground(new java.awt.Color(51, 153, 0));
        new_StudentList_Button.setForeground(new java.awt.Color(255, 255, 255));
        new_StudentList_Button.setText("NEW");
        new_StudentList_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_StudentList_ButtonActionPerformed(evt);
            }
        });

        delete_StudentList_Button.setBackground(new java.awt.Color(255, 0, 0));
        delete_StudentList_Button.setForeground(new java.awt.Color(255, 255, 255));
        delete_StudentList_Button.setText("DELETE");

        javax.swing.GroupLayout student_List_PanelLayout = new javax.swing.GroupLayout(student_List_Panel);
        student_List_Panel.setLayout(student_List_PanelLayout);
        student_List_PanelLayout.setHorizontalGroup(
                student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(student_List_PanelLayout.createSequentialGroup()
                                .addGroup(student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(student_List_PanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel5)
                                                                .addGroup(student_List_PanelLayout.createSequentialGroup()
                                                                        .addComponent(firstName_StudentList_Label)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(firstName_StudentList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(lastName_StudentList_Label)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(lastName_StudentList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(email_StudentList_Label)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(email_StudentList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(search_StudentList_Button)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(reset_StudentList_Button)))))
                                        .addGroup(student_List_PanelLayout.createSequentialGroup()
                                                .addGap(224, 224, 224)
                                                .addComponent(new_StudentList_Button)
                                                .addGap(140, 140, 140)
                                                .addComponent(delete_StudentList_Button)))
                                .addContainerGap(33, Short.MAX_VALUE))
        );
        student_List_PanelLayout.setVerticalGroup(
                student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(student_List_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstName_StudentList_Label)
                                        .addComponent(firstName_StudentList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastName_StudentList_Label)
                                        .addComponent(lastName_StudentList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(email_StudentList_Label)
                                        .addComponent(email_StudentList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(search_StudentList_Button)
                                        .addComponent(reset_StudentList_Button))
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(new_StudentList_Button)
                                        .addComponent(delete_StudentList_Button))
                                .addContainerGap(92, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("Add Attendance");

        jLabel3.setText("Subject Name : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Date : ");

        submit_AddAttendance_Button.setBackground(new java.awt.Color(0, 0, 255));
        submit_AddAttendance_Button.setForeground(new java.awt.Color(255, 255, 255));
        submit_AddAttendance_Button.setText("SUBMIT");
        submit_AddAttendance_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_AddAttendance_ButtonActionPerformed(evt);
            }
        });

        reset_AddAttendance_Button.setBackground(new java.awt.Color(0, 0, 255));
        reset_AddAttendance_Button.setForeground(new java.awt.Color(255, 255, 255));
        reset_AddAttendance_Button.setText("RESET");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Make Attendance");

        Attendance_Table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String [] {
                        "#", "Name", "Present"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Attendance_Table);

        save_AttendancePanel_Button.setBackground(new java.awt.Color(0, 0, 255));
        save_AttendancePanel_Button.setForeground(new java.awt.Color(255, 255, 255));
        save_AttendancePanel_Button.setText("SAVE");

        reset_AttendancePanel_Button.setBackground(new java.awt.Color(255, 0, 0));
        reset_AttendancePanel_Button.setForeground(new java.awt.Color(255, 255, 255));
        reset_AttendancePanel_Button.setText("RESET");

        javax.swing.GroupLayout AttendancePanelLayout = new javax.swing.GroupLayout(AttendancePanel);
        AttendancePanel.setLayout(AttendancePanelLayout);
        AttendancePanelLayout.setHorizontalGroup(
                AttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AttendancePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(AttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3)
                                        .addGroup(AttendancePanelLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(AttendancePanelLayout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(save_AttendancePanel_Button)
                                .addGap(247, 247, 247)
                                .addComponent(reset_AttendancePanel_Button)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AttendancePanelLayout.setVerticalGroup(
                AttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AttendancePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(AttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(save_AttendancePanel_Button)
                                        .addComponent(reset_AttendancePanel_Button))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layeredPanel_AddAttendance.setLayer(AttendancePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layeredPanel_AddAttendanceLayout = new javax.swing.GroupLayout(layeredPanel_AddAttendance);
        layeredPanel_AddAttendance.setLayout(layeredPanel_AddAttendanceLayout);
        layeredPanel_AddAttendanceLayout.setHorizontalGroup(
                layeredPanel_AddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AttendancePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layeredPanel_AddAttendanceLayout.setVerticalGroup(
                layeredPanel_AddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layeredPanel_AddAttendanceLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(AttendancePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout add_Attendance_PanelLayout = new javax.swing.GroupLayout(add_Attendance_Panel);
        add_Attendance_Panel.setLayout(add_Attendance_PanelLayout);
        add_Attendance_PanelLayout.setHorizontalGroup(
                add_Attendance_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Attendance_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(add_Attendance_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(add_Attendance_PanelLayout.createSequentialGroup()
                                                .addGroup(add_Attendance_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(layeredPanel_AddAttendance)
                                                        .addGroup(add_Attendance_PanelLayout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_Attendance_PanelLayout.createSequentialGroup()
                                                .addGroup(add_Attendance_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                                .addGroup(add_Attendance_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addGroup(add_Attendance_PanelLayout.createSequentialGroup()
                                                                .addComponent(date_AddAttendance_Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(68, 68, 68)
                                                                .addComponent(submit_AddAttendance_Button)
                                                                .addGap(64, 64, 64)
                                                                .addComponent(reset_AddAttendance_Button)))
                                                .addGap(78, 78, 78))))
        );
        add_Attendance_PanelLayout.setVerticalGroup(
                add_Attendance_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Attendance_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGroup(add_Attendance_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_Attendance_PanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(add_Attendance_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(submit_AddAttendance_Button)
                                                        .addComponent(reset_AddAttendance_Button))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(add_Attendance_PanelLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addGroup(add_Attendance_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(add_Attendance_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(date_AddAttendance_Calendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))))
                                .addComponent(layeredPanel_AddAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel7.setText("Attendance List");

        attendance_List_Table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "#", "Subject Name", "Student Name", "Semester", "Status"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(attendance_List_Table);

        subjectName_AttendanceList_Label.setText("Subject Name");

        studentName_AttendanceList_Label.setText("Student Name");

        search_AttendanceList_Button.setBackground(new java.awt.Color(0, 0, 255));
        search_AttendanceList_Button.setForeground(new java.awt.Color(255, 255, 255));
        search_AttendanceList_Button.setText("SEARCH");

        reset_AttendanceList_Button.setBackground(new java.awt.Color(0, 0, 255));
        reset_AttendanceList_Button.setForeground(new java.awt.Color(255, 255, 255));
        reset_AttendanceList_Button.setText("RESET");

        javax.swing.GroupLayout attendance_List_PanelLayout = new javax.swing.GroupLayout(attendance_List_Panel);
        attendance_List_Panel.setLayout(attendance_List_PanelLayout);
        attendance_List_PanelLayout.setHorizontalGroup(
                attendance_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(attendance_List_PanelLayout.createSequentialGroup()
                                .addGroup(attendance_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(attendance_List_PanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(attendance_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addGroup(attendance_List_PanelLayout.createSequentialGroup()
                                                                .addComponent(subjectName_AttendanceList_Label)
                                                                .addGap(24, 24, 24)
                                                                .addComponent(subjectName_AttendanceList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(studentName_AttendanceList_Label)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(studentName_AttendanceList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(34, 34, 34)
                                                                .addComponent(search_AttendanceList_Button)
                                                                .addGap(37, 37, 37)
                                                                .addComponent(reset_AttendanceList_Button))))
                                        .addGroup(attendance_List_PanelLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(18, Short.MAX_VALUE))
        );
        attendance_List_PanelLayout.setVerticalGroup(
                attendance_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(attendance_List_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addGap(35, 35, 35)
                                .addGroup(attendance_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(subjectName_AttendanceList_Label)
                                        .addComponent(studentName_AttendanceList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studentName_AttendanceList_Label)
                                        .addComponent(subjectName_AttendanceList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(search_AttendanceList_Button)
                                        .addComponent(reset_AttendanceList_Button))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(32, Short.MAX_VALUE))
        );

        layered_Panel.setLayer(home_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(add_Student_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(student_List_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(add_Attendance_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(attendance_List_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layered_PanelLayout = new javax.swing.GroupLayout(layered_Panel);
        layered_Panel.setLayout(layered_PanelLayout);
        layered_PanelLayout.setHorizontalGroup(
                layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layered_PanelLayout.createSequentialGroup()
                                .addComponent(home_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(add_Student_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(9, 9, 9)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(student_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(15, 15, 15)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layered_PanelLayout.createSequentialGroup()
                                        .addComponent(add_Attendance_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(attendance_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layered_PanelLayout.setVerticalGroup(
                layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layered_PanelLayout.createSequentialGroup()
                                .addComponent(home_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(add_Student_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(student_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(12, 12, 12)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addComponent(add_Attendance_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 15, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(attendance_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
        );

        home_Menu.setText("Home");

        home_MenuItem.setText("Home");
        home_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_MenuItemActionPerformed(evt);
            }
        });
        home_Menu.add(home_MenuItem);

        jMenuBar1.add(home_Menu);

        student_menu.setText("Student");

        addStudent_MenuItem.setText("Add Student");
        addStudent_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudent_MenuItemActionPerformed(evt);
            }
        });
        student_menu.add(addStudent_MenuItem);

        studentList_MenuItem.setText("Student List");
        studentList_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentList_MenuItemActionPerformed(evt);
            }
        });
        student_menu.add(studentList_MenuItem);

        jMenuBar1.add(student_menu);

        attendance_Menu.setText("Attendance");

        addAttendance_MenuItem.setText("Add Attendance");
        addAttendance_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAttendance_MenuItemActionPerformed(evt);
            }
        });
        attendance_Menu.add(addAttendance_MenuItem);

        attendanceList_MenuItem.setText("Attendance List");
        attendanceList_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceList_MenuItemActionPerformed(evt);
            }
        });
        attendance_Menu.add(attendanceList_MenuItem);

        jMenuBar1.add(attendance_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(layered_Panel))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(layered_Panel))
        );

        pack();
    }// </editor-fold>

    private void addStudent_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        home_Panel.setVisible(false);
        add_Student_Panel.setVisible(true);
        student_List_Panel.setVisible(false);
        add_Attendance_Panel.setVisible(false);
        attendance_List_Panel.setVisible(false);


    }

    private void addAttendance_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        home_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Attendance_Panel.setVisible(true);
        attendance_List_Panel.setVisible(false);
        AttendancePanel.setVisible(false);
    }

    private void student_email_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void home_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        home_Panel.setVisible(true);
        add_Student_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Attendance_Panel.setVisible(false);
        attendance_List_Panel.setVisible(false);


    }

    private void studentList_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        home_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        student_List_Panel.setVisible(true);
        add_Attendance_Panel.setVisible(false);
        attendance_List_Panel.setVisible(false);


    }

    private void attendanceList_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        home_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Attendance_Panel.setVisible(false);
        attendance_List_Panel.setVisible(true);
    }

    private void save_AddStudent_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String stdFname = student_FirstName_TextField.getText();
        String stdLname = student_LastName_TextField.getText();
        String StudentId = student_email_TextField.getText();
        Object obj = student_Gender_ComboBox.getSelectedItem();
        String stdGender = (String) obj;
        String stdPhoneno = student_Mobile_TextField.getText();
        String password =student_Password_PasswordField.getText();
        String confirmPassword = student_ConfirmPassword_PasswordField.getText();
        String semester = (String) semester_ComboBox.getSelectedItem();
        String course = (String)courseName_ComboBox.getSelectedItem();
        String parentsphone = parents_mobile_TextField.getText();
        String parentsemail = parents_Email_TextField.getText();
        if (password.equals(confirmPassword)) {

            Student std = new Student(StudentId, stdFname,stdLname ,stdGender,stdPhoneno, password,course,semester, parentsphone, parentsemail);
            StudentController sc = new StudentController();
            int insert = sc.registerStudentpreparedStatement(std);
            if (insert > 0)
                javax.swing.JOptionPane.showMessageDialog(null, "Successfully registered");
            else
                javax.swing.JOptionPane.showMessageDialog(null, "Failed to register");
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Password and Confirm Password does not match");
            student_Password_PasswordField.requestFocus();
        }

    }

    private void new_StudentList_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        home_Panel.setVisible(false);
        add_Student_Panel.setVisible(true);
        student_List_Panel.setVisible(false);
        add_Attendance_Panel.setVisible(false);
        attendance_List_Panel.setVisible(false);

    }

    private void submit_AddAttendance_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        AttendancePanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel AttendancePanel;
    private javax.swing.JTable Attendance_Table;
    private javax.swing.JMenuItem addAttendance_MenuItem;
    private javax.swing.JMenuItem addStudent_MenuItem;
    private javax.swing.JPanel add_Attendance_Panel;
    private javax.swing.JPanel add_Student_Panel;
    private javax.swing.JMenuItem attendanceList_MenuItem;
    private javax.swing.JPanel attendance_List_Panel;
    private javax.swing.JTable attendance_List_Table;
    private javax.swing.JMenu attendance_Menu;
    private javax.swing.JComboBox<String> courseName_ComboBox;
    private javax.swing.JLabel courseName_Label;
    private com.toedter.calendar.JDateChooser date_AddAttendance_Calendar;
    private javax.swing.JButton delete_StudentList_Button;
    private javax.swing.JLabel email_Label;
    private javax.swing.JLabel email_StudentList_Label;
    private javax.swing.JTextField email_StudentList_TextField;
    private javax.swing.JLabel firstName_StudentList_Label;
    private javax.swing.JTextField firstName_StudentList_TextField;
    private javax.swing.JMenu home_Menu;
    private javax.swing.JMenuItem home_MenuItem;
    private javax.swing.JPanel home_Panel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lastName_StudentList_Label;
    private javax.swing.JTextField lastName_StudentList_TextField;
    private javax.swing.JLayeredPane layeredPanel_AddAttendance;
    private javax.swing.JLayeredPane layered_Panel;
    private javax.swing.JButton new_StudentList_Button;
    private javax.swing.JLabel parents_Email_Label;
    private javax.swing.JTextField parents_Email_TextField;
    private javax.swing.JLabel parents_Mobile_Label;
    private javax.swing.JTextField parents_mobile_TextField;
    private javax.swing.JButton reset_AddAttendance_Button;
    private javax.swing.JButton reset_AddStudent_Button;
    private javax.swing.JButton reset_AttendanceList_Button;
    private javax.swing.JButton reset_AttendancePanel_Button;
    private javax.swing.JButton reset_StudentList_Button;
    private javax.swing.JButton save_AddStudent_Button;
    private javax.swing.JButton save_AttendancePanel_Button;
    private javax.swing.JButton search_AttendanceList_Button;
    private javax.swing.JButton search_StudentList_Button;
    private javax.swing.JComboBox<String> semester_ComboBox;
    private javax.swing.JLabel semester_Label;
    private javax.swing.JMenuItem studentList_MenuItem;
    private javax.swing.JTable studentList_Table;
    private javax.swing.JLabel studentName_AttendanceList_Label;
    private javax.swing.JTextField studentName_AttendanceList_TextField;
    private javax.swing.JLabel student_ConfirmPassword_Label;
    private javax.swing.JPasswordField student_ConfirmPassword_PasswordField;
    private javax.swing.JLabel student_DateOfBirth_Label;
    private javax.swing.JTextField student_DateOfBirth_TextField;
    private javax.swing.JLabel student_FirstName_Label;
    private javax.swing.JTextField student_FirstName_TextField;
    private javax.swing.JComboBox<String> student_Gender_ComboBox;
    private javax.swing.JLabel student_LastName_Label;
    private javax.swing.JTextField student_LastName_TextField;
    private javax.swing.JPanel student_List_Panel;
    private javax.swing.JLabel student_MobileNumber_Label;
    private javax.swing.JTextField student_Mobile_TextField;
    private javax.swing.JLabel student_Password_Label;
    private javax.swing.JPasswordField student_Password_PasswordField;
    private javax.swing.JTextField student_email_TextField;
    private javax.swing.JMenu student_menu;
    private javax.swing.JLabel subjectName_AttendanceList_Label;
    private javax.swing.JTextField subjectName_AttendanceList_TextField;
    private javax.swing.JButton submit_AddAttendance_Button;
    // End of variables declaration
}
